-- 数据库备份记录表
CREATE TABLE IF NOT EXISTS backup_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '备份ID',
    backup_type VARCHAR(20) NOT NULL COMMENT '备份类型：FULL-全量 INCREMENTAL-增量',
    file_name VARCHAR(200) NOT NULL COMMENT '文件名',
    file_path VARCHAR(500) NOT NULL COMMENT '文件路径',
    file_size BIGINT DEFAULT 0 COMMENT '文件大小（字节）',
    status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS' COMMENT '状态：SUCCESS/FAILED',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB COMMENT='数据库备份记录表';
